# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        type: choice
        required: true
        options:
          - DEV
          - STG
  workflow_call:
    # Inputs the workflow accepts.
    inputs:
      name:
        type: string
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'DEV'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    name: Deploy ${{ github.event.inputs.name }}
    # The type of runner that the job will run on
    env:
      name: ${{ github.event.inputs.name || inputs.name }}
    environment: ${{ github.event.inputs.name || inputs.name }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "${{ env.name }}"
